// <auto-generated />
namespace UniversityManagementApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class version3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version3));
        
        string IMigrationMetadata.Id
        {
            get { return "201710180908033_version3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
